---
title: "Homework 4"
author: '[Group names]'
date: "9/26/2019"
output: 
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, message = FALSE)
```

## Packages

```{r packages}
require(tidyverse)
```

## Data

```{r read-data}
nasa <- readRDS(file = "nasa.rds")
```

<!--
```{r task}
#easy_df <- data.frame(lapply(easy_df, unlist), stringsAsFactoers=FALSE)
var_names <- names(nasa[[1]])
easy_part <- map(nasa, `[`, var_names[1:9])
easy_df <- do.call(rbind, easy_part) %>%
  data.frame(stringsAsFactors = FALSE) %>%
  lapply(as.character) %>%
  data.frame(stringsAsFactors = FALSE)

geo_coord <- map(nasa, list("geolocation", "coordinates"))
features <- map(nasa, `[[`, "features") %>%
  map(unlist)
nasa_df <- easy_df %>%
  mutate("features" = features,
         "geo_coord" = geo_coord)
nasa_df[nasa_df=='NULL'] <- NA
```
-->

## Task1
```{r task-1}
nasa_df <- nasa %>%
  lapply(unlist) %>%
  lapply(data.frame, stringsAsFactors = FALSE) %>%
  lapply(t) %>%
  lapply(data.frame, stringsAsFactors = FALSE) %>%
  bind_rows()
```


## Task2

### select useful columns
```{r select-cols}
nasa_df <- nasa_df %>%
  select(-(22:23)) %>%
  select(-geolocation.type)
```

### remove duplicates
```{r remove-dup}
nasa_df <- nasa_df %>%
  filter(!duplicated(nasa_df))
```


### clean id
```{r id}
nasa_df$id <- as.integer(nasa_df$id)
```

### clean date time
```{r date-time}
nasa_df$year <- str_replace(nasa_df$year, "T+", " ")
nasa_df$year <- str_replace(nasa_df$year, "\\..*", "")
nasa_df <- nasa_df %>%
  separate(col=year, into=c('year', 'month', 'day'), sep='-') %>%
  separate(col=day, into=c('day', 'hours'), sep=" ") %>%
  separate(col=hours, into=(c('hours', 'minutes', 'seconds')), sep=':')
time_names <- c('year', 'month', 'day', 'hours', 'minutes', 'seconds')
nasa_df[time_names] <- nasa_df[time_names] %>%
  map(as.integer)
```

### clean coordinates
```{r geo-coords}
# rename column
names(nasa_df)[names(nasa_df) == 'geolocation.coordinates1'] <- 'geo_coord1'
names(nasa_df)[names(nasa_df) == 'geolocation.coordinates2'] <- 'geo_coord2'
nasa_df$geo_coord1 <- nasa_df$geo_coord1 %>%
  str_extract("-?\\d*\\.?\\d*$") %>%
  as.numeric()
nasa_df$geo_coord2 <- nasa_df$geo_coord2 %>%
  str_extract("-?\\d*\\.?\\d*$") %>%
  as.numeric()
nasa_df$geo_coords <- map2(nasa_df$geo_coord1, nasa_df$geo_coord2, ~ c(.x, .y))
nasa_df <- nasa_df %>%
  select(-'geo_coord1', -'geo_coord2')
```

### clean features
```{r}
nasa_df$features[nasa_df$features == 'n/a'] <- NA
nasa_df$features[nasa_df$features == 'NA'] <- NA
nasa_df$features[nasa_df$features == 'unknown'] <- NA
for (feature in names(nasa_df)[15:22])
{
  nasa_df$features <- map2(nasa_df$features, nasa_df[[feature]], ~c(.x, .y))
}
nasa_df <- nasa_df %>%
  select(-('features1':'features8'))
nasa_df$features <- nasa_df$features %>%
  map(function (x) {x[!is.na(x)]})
```


```{r show=FALSE}
nasa_df
```

